<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLEZAjoE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLEZAjoE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLEZAjoE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLEZAjoE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLEZAjoE\App_KernelDevDebugContainer([
    'container.build_hash' => 'LEZAjoE',
    'container.build_id' => '02b52096',
    'container.build_time' => 1750335604,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLEZAjoE');
