<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG80xrVR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG80xrVR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG80xrVR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG80xrVR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG80xrVR\App_KernelDevDebugContainer([
    'container.build_hash' => 'G80xrVR',
    'container.build_id' => 'b03c9f3d',
    'container.build_time' => 1750255032,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG80xrVR');
